// State registry for the multi-state Voter Verification Centre.
//
// Each entry declares the state's identity, its official links, its SIR
// timeline, the language pair offered by the toggle, and copy overrides that
// replace generic strings in app.js COPY for that state. Keys absent from an
// override fall back to the generic dictionary, so only state-specific
// wording lives here. `enabled: false` states are hidden from the switcher.
window.SIR_STATES = Object.freeze({
  defaultState: "karnataka",
  states: {
    karnataka: {
      slug: "karnataka",
      expectedConstituencies: 224,
      enabled: true,
      nameEn: "Karnataka",
      nameLocal: "ಕರ್ನಾಟಕ",
      localeKey: "kn",
      localeLabel: "ಕನ್ನಡ",
      board: {
        image: "assets/voter-verification-centre-en-kn-v1.png",
        alt: "Voter Verification Centre, ಮತದಾರರ ದೃಢೀಕರಣ ಕೇಂದ್ರ, not official",
      },
      locationsUrl: "locations.json?v=2026-08-26",
      helplines: [
        { label: "1950", tel: "1950" },
        { label: "1800 4255 1950", tel: "180042551950" },
      ],
      links: {
        ceoHome: "https://ceo.karnataka.gov.in/",
        asddoPage: "https://ceo.karnataka.gov.in/asddo.html",
        noticesPage: "https://ceo.karnataka.gov.in/notices_issued.html",
        contacts: "https://ceo.karnataka.gov.in/vfc/details/",
        ceoUpdate: "https://ceo.karnataka.gov.in/uploads/Press%20Note%20-%2008.08,2026.pdf",
        eciSchedule: "https://cdn.s3waas.gov.in/s3eefc9e10ebdc4a2333b42b2dbb8f27b6/uploads/2026/08/17861123926261.pdf",
      },
      chalk: { asddo: "10,778,213", roll: "44,626,362", notice: "4,096,752" },
      methodStats: [
        { value: "10,778,213", copyKey: "stat1" },
        { value: "58,948", copyKey: "stat2" },
        { value: "44,626,362", copyKey: "stat3" },
        { value: "60,922", copyKey: "stat4" },
        { value: "224 / 224", copyKey: "stat5" },
        { value: "4,096,752", copyKey: "statNotice", id: "notice-method-count" },
        { value: "435,687", copyKey: "stat6" },
      ],
      hasCoverageNote: true,
      copy: {
        en: {
          claimsDeadline: "23 September 2026",
          claimsDeadlineShort: "23 September",
          eyebrow: "Karnataka SIR 2026 · Draft roll, ASDDO and clarification notices",
          title: "Check your Karnataka voter record.",
          chalkSnapshot: "Two voter indexes + exact EPIC notice checks · all 224 constituencies",
          verdictAsddoBody: "The file gives the reason shown below. Check the official draft roll, then file Form 6 with the SIR Declaration by {claimsDeadline} when your name is missing there.",
          verdictRollBody: "Open ECI’s official search and check the polling station. For a changed address or spelling, file Form 8 by {claimsDeadline}.",
          overlapDifferentBooth: "This EPIC appears in an ASDDO file for one booth and in the draft roll for another. Open the draft entry and check the address, then use Form 8 by {claimsDeadline} for a change.",
          step2Lead: "File Form 6 by {claimsDeadlineShort}.",
          step4Body: "Send it by {claimsDeadlineShort} through the portal or give it to the ERO for your current address.",
          datesEyebrow: "Schedule checked 26 August 2026",
          d1Label: "24 Aug 2026",
          d1Body: "Karnataka published the draft electoral roll.",
          d2Label: "By 23 Sep 2026",
          d2Body: "Claims and objections close. Use Form 6 for a missing name; Form 8 covers a move or correction.",
          d3Label: "By 22 Oct 2026",
          d3Body: "EROs finish the notice phase and decide filings by this date.",
          d4Label: "27 Oct 2026",
          d4Body: "The final electoral roll is due on this date.",
          ceoHome: "CEO Karnataka",
          helpline: "Karnataka voter helplines:",
          ceoUpdate: "CEO guidance, 8 August",
          eciSchedule: "Revised SIR schedule, 7 August",
          methodNote: "The search first identifies a voter in Karnataka’s ASDDO files or draft roll, then checks that EPIC ID in the clarification notices. It does not run a separate name search across notices. PDF text can carry spelling errors; the counts describe each source layer.",
          aboutIndex: "DataChutney built this unofficial search from public ASDDO files, Karnataka’s draft electoral roll and the CEO’s published clarification notices. Check every match in ECI’s official search; your ERO decides each electoral-roll application.",
          coverageBody: "This constituency stays visible so the gap is clear. Check CEO Karnataka or ask your BLO / ERO.",
          noticeCoverageTitle: "Some clarification-notice coverage is incomplete.",
          noticeCoverageBody: " Available records are included, but 50 Ballari (Bellary), 29 Chitradurga and 4 Vijayapura source files became unavailable before retry.",
          ceoPage: "CEO Karnataka ASDDO page",
          ceoNotices: "CEO Karnataka notices issued",
        },
      },
    },

    telangana: {
      slug: "telangana",
      expectedConstituencies: 119,
      enabled: true,
      apiBaseUrl: "https://web-telangana-production.up.railway.app",
      nameEn: "Telangana",
      nameLocal: "తెలంగాణ",
      localeKey: "te",
      localeLabel: "తెలుగు",
      board: {
        image: "assets/voter-verification-centre-en-te-v1.png",
        alt: "Voter Verification Centre, ఓటరు ధృవీకరణ కేంద్రం, not official",
      },
      locationsUrl: "locations-telangana.json?v=1",
      helplines: [{ label: "1950", tel: "1950" }],
      links: {
        ceoHome: "https://ceotelangana.nic.in/",
        asddoPage: "https://voters.eci.gov.in/",
        noticesPage: "https://ceotserms2.telangana.gov.in/SIR_Discprency/SIR_Discprency.aspx",
        contacts: "https://ceotelangana.nic.in/",
        ceoUpdate: "https://ceotelangana.nic.in/",
        eciSchedule: "https://www.eci.gov.in/",
      },
      chalk: { asddo: "7,336,007", roll: "26,487,213", notice: "9,197,005" },
      methodStats: [
        { value: "7,336,007", copyKey: "stat1" },
        { value: "36,330", copyKey: "stat2" },
        { value: "26,487,213", copyKey: "stat3" },
        { value: "36,353", copyKey: "stat4" },
        { value: "119 / 119", copyKey: "stat5" },
        { value: "9,197,005", copyKey: "statNotice", id: "notice-method-count" },
      ],
      hasCoverageNote: true,
      copy: {
        en: {
          claimsDeadline: "10 October 2026",
          claimsDeadlineShort: "10 October",
          eyebrow: "Telangana SIR 2026 · Draft roll, ASD deletion reports and discrepancy notices",
          title: "Check your Telangana voter record.",
          chalkAsddoIndexed: "ASD deletion records",
          chalkSnapshot: "Two voter indexes + exact EPIC notice checks · all 119 constituencies",
          statusAsddo: "ASD deletion record",
          checkAsddoLabel: "ASD deletion report",
          stepsTitle: "If your record appears in an ASD deletion report",
          verdictAsddoTitle: "This record appears in an ASD deletion report.",
          verdictAsddoBody: "The report gives the reason shown below. Check the official draft roll, then file Form 6 with the SIR Declaration by {claimsDeadline} when your name is missing there.",
          verdictRollBody: "Open ECI’s official search and check the polling station. For a changed address or spelling, file Form 8 by {claimsDeadline}.",
          overlapDifferentBooth: "This EPIC appears in an ASD report for one booth and in the draft roll for another. Open the draft entry and check the address, then use Form 8 by {claimsDeadline} for a change.",
          step2Lead: "File Form 6 by {claimsDeadlineShort}.",
          step4Body: "Send it by {claimsDeadlineShort} through the portal, or give it to the ERO for your current address.",
          datesEyebrow: "Schedule checked 9 September 2026",
          d1Label: "17 Aug 2026",
          d1Body: "Telangana published the draft electoral roll.",
          d2Label: "By 10 Oct 2026",
          d2Body: "Claims and objections close (extended from 16 September). Use Form 6 for a missing name; Form 8 covers a move or correction.",
          d3Label: "By 5 Nov 2026",
          d3Body: "EROs finish the notice phase and decide filings by this date.",
          d4Label: "19 Oct – 9 Nov 2026",
          d4Body: "The final electoral roll is published in this window.",
          ceoHome: "CEO Telangana",
          helpline: "Telangana voter helpline:",
          ceoUpdate: "CEO Telangana updates",
          eciSchedule: "ECI SIR schedule",
          ceoPage: "Official ASD reports (ECI)",
          ceoNotices: "CEO Telangana discrepancy notices",
          statusNotice: "Present · discrepancy notice issued",
          verdictNoticeTitle: "Your name appears in the draft roll, and a discrepancy notice has been issued.",
          verdictNoticeBody: "Your name is on the draft roll, but the record has a discrepancy the ERO wants resolved. Read the published reason below and submit the requested documents through the Voters\u2019 Service Portal or your ERO before {claimsDeadline} \u2014 an unresolved notice can affect the final roll.",
          verifyNoticeLine: "Your name is present in the draft roll. Resolve the notice before {claimsDeadline} \u2014 submit documents via the Voters\u2019 Service Portal or contact your ERO.",
          newClarificationBadge: "NEW \u00b7 Now includes the discrepancy-notice lists",
          chalkNoticeIndexed: "voters with discrepancy notices",
          checkNoticeLabel: "Discrepancy notices",
          statNotice: "rows in published discrepancy-notice lists.",
          stat1: "ASD deletion-report records carrying a stated reason.",
          stat2: "ASD report PDFs indexed.",
          stat4: "draft-roll electoral parts represented.",
          methodNote: "The search first identifies a voter in Telangana’s ASD deletion reports or draft roll, then checks that EPIC ID in the published discrepancy notices. It does not run a separate name search across notices. PDF text can carry spelling errors; the counts describe each source layer.",
          aboutIndex: "DataChutney built this unofficial search from ECI’s published ASD deletion reports, Telangana’s draft electoral roll and the CEO’s published discrepancy notices. Check every match in ECI’s official search; your ERO decides each electoral-roll application.",
          coverageBody: "This constituency stays visible so the gap is clear. Check CEO Telangana or ask your BLO / ERO.",
          noticeCoverageTitle: "Some discrepancy-notice coverage is incomplete.",
          noticeCoverageBody: " Available records are included, but 523 of 36,353 part lists had not been published at the official source when this index was built.",
        },      },
    },

    delhi: {
      slug: "delhi",
      expectedConstituencies: 70,
      enabled: false,
      nameEn: "Delhi",
      nameLocal: "दिल्ली",
      localeKey: "hi",
      localeLabel: "हिन्दी",
      board: {
        image: "assets/voter-verification-centre-en-hi-v1.png",
        alt: "Voter Verification Centre, मतदाता सत्यापन केंद्र, not official",
      },
      locationsUrl: "locations-delhi.json?v=1",
      helplines: [{ label: "1950", tel: "1950" }],
      links: {
        ceoHome: "https://www.ceodelhi.gov.in/",
        asddoPage: "https://voters.eci.gov.in/",
        noticesPage: "https://www.ceodelhi.gov.in/",
        contacts: "https://www.ceodelhi.gov.in/",
        ceoUpdate: "https://www.ceodelhi.gov.in/",
        eciSchedule: "https://www.eci.gov.in/",
      },
      chalk: { asddo: "4,756,722", roll: "0", notice: "0" },
      methodStats: [
        { value: "4,756,722", copyKey: "stat1" },
        { value: "14,947", copyKey: "stat2" },
        { value: "70 / 70", copyKey: "stat5" },
      ],
      hasCoverageNote: false,
      copy: { en: {}, hi: {} },
    },

    maharashtra: {
      slug: "maharashtra",
      expectedConstituencies: 288,
      enabled: false,
      nameEn: "Maharashtra",
      nameLocal: "महाराष्ट्र",
      localeKey: "mr",
      localeLabel: "मराठी",
      board: {
        image: "assets/voter-verification-centre-en-mr-v1.png",
        alt: "Voter Verification Centre, मतदार पडताळणी केंद्र, not official",
      },
      locationsUrl: "locations-maharashtra.json?v=1",
      helplines: [{ label: "1950", tel: "1950" }],
      links: {
        ceoHome: "https://ceoelection.maharashtra.gov.in/",
        asddoPage: "https://voters.eci.gov.in/",
        noticesPage: "https://ceoelection.maharashtra.gov.in/",
        contacts: "https://ceoelection.maharashtra.gov.in/",
        ceoUpdate: "https://ceoelection.maharashtra.gov.in/",
        eciSchedule: "https://www.eci.gov.in/",
      },
      chalk: { asddo: "20,688,200", roll: "0", notice: "0" },
      methodStats: [
        { value: "20,688,200", copyKey: "stat1" },
        { value: "100,164", copyKey: "stat2" },
        { value: "288 / 288", copyKey: "stat5" },
      ],
      hasCoverageNote: false,
      copy: { en: {}, mr: {} },
    },
  },
});
